### ISSUE TITLE
Open a stream without requests

### ISSUE THREAD

**Issue by andreafresa** [mpetazzoni/sseclient#22]
Hello,
I am using SSE for interoperate with a Leshan LWM2M Server. 
I need to open a stream.
In curl I would do like this: 
curl -N -H "Accept:text/event-stream" http://server.com/event?ep=hostname
How can I do it with your library?

**Comment by mpetazzoni** [comment]
I'm not entirely sure what your question is. If you mean how to open an SSE stream without using the `requests` library, the README shows how to do it with `urllib3` as well.

**Comment by bartmoons** [comment]
You can do this by modifying the headers of your request, by default sseclient doesn't set the `Accept: text/event-stream`.
Use the following:
```
headers = { 
    'Accept': "text/event-stream"
}

response = requests.get(uri, stream=True, headers=headers)
client = sseclient.SSEClient(response)
for event in client.events():
    pprint.pprint(json.loads(event.data))
```

**Comment by mpetazzoni** [comment]
`SSEClient()` isn't responsible for making the request, it works directly off a streamable event source; however that's obtained is left to the application since people may have more specific needs about which library they employ, or where/how their stream of Server-Sent Events may be coming from.

That being said, I should document setting that header in the README examples, so I'll do that.
